//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bed
    {
        public Bed()
        {
            this.Visits = new HashSet<Visit>();
        }
    
        public int BedID { get; set; }
        public string Ward_Type { get; set; }
        public int Bed_Number { get; set; }
        public decimal Rate_Per_Day { get; set; }
        public bool Occupied { get; set; }
        public Nullable<int> OccupiedID { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
