//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BedView
    {
        public string Ward_Type { get; set; }
        public int Number { get; set; }
        public decimal Rate_Per_Day { get; set; }
        public bool Occupied { get; set; }
        public string Occupied_By { get; set; }
    }
}
