//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Visits = new HashSet<Visit>();
        }
    
        public int DoctorID { get; set; }
        public string Name { get; set; }
        public string DoctorType { get; set; }
        public string Address { get; set; }
        public string HomePhone { get; set; }
        public string Mobile { get; set; }
    
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
