//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Beds = new HashSet<Bed>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int PatientID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Address { get; set; }
        public string Phone__Home_Work_ { get; set; }
        public string Phone_Mobile_ { get; set; }
        public string Emerg__Contact__Name_ { get; set; }
        public string Emerg__Contact__Number_ { get; set; }
        public System.DateTime Date_Of_Registration { get; set; }
    
        public virtual ICollection<Bed> Beds { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
